### PR TITLE
fix: Icon buttons on hover state should be a bit darker

### LINKED ISSUE #559: Icon buttons on hover state should be a bit darker
**Describe the bug**
Notice that icon color and text color is a bit darker

image

**To Reproduce**

1. Open project groups page
2. Notice that the buttons color on hover is not a bit darker as in Zeplin (see screenshot)

**Expected behavior**
Make icon & text color on hover a bit darker as in Zeplin

**Additional context**

### PR DESCRIPTION
**Pull request by solid-daniyilyevtyushkin**
Fixes #559 

## Checklist

- [x] Documented
- [x] Unit tested
- [x] Component tested
- [x] Driver tested

### CODE REVIEW

File: metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart [hunk 1]
```diff
@@ -59,38 +59,55 @@ class _ProjectGroupCardState extends State<ProjectGroupCard> {
...
-                          fit: BoxFit.contain,
-                          color: theme.accentColor,
-                        ),
-                        label: CommonStrings.delete,
-                        labelStyle: TextStyle(
-                          color: theme.accentColor,
-                        ),
+                      TappableArea(
+                        builder: (context, isHovered, _) {
+                          return IconLabelButton(
```
Comment (solid-vladlaba) [inline metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart:64]: Maybe we can introduce the hover parameters to the IconLabelButton and move the TappableArea logic to the IconLabelButton implementation? Also, I suppose we should think about implementing a similar approach as for MetricsButton. E.g., create the MetricsIconLabelButton and introduce the PositiveIconLabelButton, Negative... and so on.

cc @illia-romanenko @vova-beloded

File: metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart [hunk 2]
```diff
@@ -111,8 +111,10 @@ class LightMetricsThemeData extends MetricsThemeData {
             borderColor: _borderColor,
             hoverColor: _cardHoverColor,
             backgroundColor: scaffoldColor,
-            accentColor: ColorConfig.accentColor,
+            accentColor: ColorConfig.accentButtonColor,
+            accentHoverColor: ColorConfig.accentButtonHoverColor,
```
Comment (solid-vladlaba) [inline metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart:115]: In addition to the suggestion below, I think we can use the MetricsButtonThemeData for MetricsIconLabelButton. I've noticed that icon buttons have similar styles in the design.

**Review by solid-vladlaba — CHANGES_REQUESTED** [review]
Well done, @solid-daniyilyevtyushkin! I've added a couple of suggestions below - please let me know what you think!

File: metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart [hunk 3]
```diff
@@ -59,34 +59,54 @@ class _ProjectGroupCardState extends State<ProjectGroupCard> {
                     mainAxisAlignment: MainAxisAlignment.spaceBetween,
                     children: <Widget>[
                       IconLabelButton(
-                        onPressed: _showEditProjectGroupDialog,
+                        onPressed: () => _showEditProjectGroupDialog(),
```
Comment (vova-beloded) [inline metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart:62]: Maybe the previous version was better?  The same for `_showDeleteProjectGroupDialog`.

File: metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart [hunk 4]
```diff
@@ -59,34 +59,54 @@ class _ProjectGroupCardState extends State<ProjectGroupCard> {
...
-                        ),
+                        iconBuilder: (context, isHovered) {
+                          return Image.network(
+                            'icons/edit.svg',
+                            width: _iconBoxSide,
+                            height: _iconBoxSide,
+                            fit: BoxFit.contain,
+                            color: isHovered
+                                ? theme.primaryButtonStyle.hoverColor
+                                : theme.primaryButtonStyle.color,
```
Comment (vova-beloded) [inline metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart:72]: Would it be better to extract it to the variable to avoid duplication? The same for `theme.accentButtonStyle`.

File: metrics/web/test/base/presentation/widgets/icon_label_button_test.dart [hunk 5]
```diff
@@ -201,43 +255,36 @@ class _IconLabelButtonTestbed extends StatelessWidget {
...
   /// Creates the instance of this testbed.
   ///
   /// Both [iconPadding] and [contentPadding] defaults to [EdgeInsets.zero].
-  /// The [label] defaults to `label`.
-  /// The [icon] defaults to [Icons.add].
   const _IconLabelButtonTestbed({
-    this.label = "label",
-    this.icon = const Icon(Icons.add),
+    this.labelBuilder,
+    this.iconBuilder,
```
Comment (vova-beloded) [inline metrics/web/test/base/presentation/widgets/icon_label_button_test.dart:272]: Maybe we can set the default params for these fields to avoid passing them in each test?

File: metrics/web/test/base/presentation/widgets/icon_label_button_test.dart [hunk 6]
```diff
@@ -80,70 +112,89 @@ void main() {
...
+          find.ancestor(
+            of: find.byType(GestureDetector),
+            matching: find.byType(MouseRegion),
+          ),
+        );
+
+        const pointerEnterEvent = PointerEnterEvent();
+        mouseRegion.onEnter(pointerEnterEvent);
+
+        await tester.pump();
```
Comment (vova-beloded) [inline metrics/web/test/base/presentation/widgets/icon_label_button_test.dart:180]: Maybe we can extract this part of the code to functions to avoid duplication?

File: metrics/web/test/project_groups/presentation/widgets/project_group_card_test.dart [hunk 7]
```diff
@@ -42,12 +43,18 @@ void main() {
     const testHoverColor = Colors.black;
     const testTitleStyle = TextStyle(color: Colors.grey);
     const testSubtitleStyle = TextStyle(color: Colors.black);
+    const primaryButtonStyle = MetricsButtonStyle(
+      color: testPrimaryColor,
```
Comment (vova-beloded) [inline metrics/web/test/project_groups/presentation/widgets/project_group_card_test.dart:47]:
```suggestion
      color: primaryButtonColor,
```
?

**Review by vova-beloded — CHANGES_REQUESTED** [review]
Great job, @solid-daniyilyevtyushkin & @solid-vladlaba! I've added a couple of suggestions - please let me know what do you think.

**Review by vova-beloded — APPROVED** [review]
LGTM, thanks @solid-daniyilyevtyushkin!

**Review by solid-vladlaba — APPROVED** [review]
LGTM, thanks @solid-daniyilyevtyushkin!:rocket:
