### PR TITLE
fix: Display error messages near input fields

### LINKED ISSUE #542: Login page - error messages near the input fields
**Describe the bug**
Display error messages like "Wrong password" etc.. near the input rather than in the toast.

**To Reproduce**
1. Type wrong password in
2. Notice error message is displayed via popup

**Expected behavior**
The error message should be displayed near the password field.

**Additional context**
Please check all messages available on the login screen - and make sure that they are displayed near the appropriate input field.

### PR DESCRIPTION
**Pull request by solid-tetianamovlian**
Fixes #542 

## Checklist

- [x] Documented
- [x] Unit tested
- [x] Component tested

### CODE REVIEW

File: metrics/web/test/auth/presentation/state/auth_notifier_test.dart [hunk 1]
```diff
@@ -274,6 +301,40 @@ void main() {
       },
     );
 
+    test(
+      ".signInWithEmailAndPassword() clears the authentication email error message on a successful sign in",
+      () {
+        when(signInUseCase.call(invalidCredentials))
+            .thenThrow(emailAuthException);
+
+        authNotifier.signInWithEmailAndPassword(invalidEmail, invalidPassword);
```
Comment (solid-vovabeloded) [inline metrics/web/test/auth/presentation/state/auth_notifier_test.dart:310]: Seems like we should add `await` here and below since this is an async method.

File: metrics/web/test/auth/presentation/state/auth_notifier_test.dart [hunk 2]
```diff
@@ -274,6 +301,40 @@ void main() {
...
+
+        expect(authNotifier.emailErrorMessage, isNotNull);
+
+        authNotifier.signInWithEmailAndPassword(
+            'valid_email@mail.mail', 'valid_password');
```
Comment (solid-vovabeloded) [inline metrics/web/test/auth/presentation/state/auth_notifier_test.dart:315]: Can we use `email` and `password` constants here and below?

File: metrics/web/test/auth/presentation/widgets/auth_form_test.dart [hunk 3]
```diff
@@ -293,6 +310,110 @@ void main() {
...
       },
     );
+
+    testWidgets(
+      "displays the email auth error message",
+      (tester) async {
+        final authNotifier = AuthNotifierMock();
+
+        when(authNotifier.isLoading).thenReturn(false);
+        when(authNotifier.emailErrorMessage).thenReturn(errorMessage);
```
Comment (solid-vovabeloded) [inline metrics/web/test/auth/presentation/widgets/auth_form_test.dart:320]: We should mock the notifier in widget tests instead of use cases. Could you, please, remove all occurrence of use case mocks?

File: metrics/web/test/auth/presentation/widgets/auth_form_test.dart [hunk 4]
```diff
@@ -337,6 +458,12 @@ class SignInErrorAuthNotifierStub extends ChangeNotifier
   @override
   String get authErrorMessage => _authExceptionDescription;
 
+  @override
```
Comment (solid-vovabeloded) [inline metrics/web/test/auth/presentation/widgets/auth_form_test.dart:461]: Seems like this stub is not used. Maybe we can remove it?

**Review by solid-vovabeloded — CHANGES_REQUESTED** [review]
Well done, @solid-maxim & @solid-tetianamovlian! I've added a couple of suggestions below - please take a look.

File: metrics/web/test/auth/presentation/state/auth_notifier_test.dart [hunk 5]
```diff
@@ -235,56 +248,110 @@ void main() {
       verifyNever(googleSignInUseCase());
     });
 
-    test(".authErrorMessage is populated when SignInUseCase throws", () {
+    test(".authErrorMessage is populated when SignInUseCase throws", () async {
```
Comment (solid-vovabeloded) [inline metrics/web/test/auth/presentation/state/auth_notifier_test.dart:251]: Should we change the description of this test to be similar to the next one?

File: metrics/web/test/auth/presentation/state/auth_notifier_test.dart [hunk 6]
```diff
@@ -235,56 +248,110 @@ void main() {
...
 
       expect(authNotifier.authErrorMessage, isNotNull);
     });
 
-    test(".authErrorMessage is populated when GoogleSignInUseCase throws", () {
-      when(googleSignInUseCase.call()).thenThrow(authException);
+    test(
+      ".emailErrorMessage is populated when the email-related error occurred during the sign-in process",
+      () async {
+        when(signInUseCase.call(any)).thenThrow(emailAuthException);
```
Comment (solid-vovabeloded) [inline metrics/web/test/auth/presentation/state/auth_notifier_test.dart:262]: Should we use the `thenAnswer` method since this is an async use case? The same for all tests below.

File: metrics/web/test/auth/presentation/state/auth_notifier_test.dart [hunk 7]
```diff
@@ -235,56 +248,110 @@ void main() {
...
     );
 
+    test(
+      ".signInWithEmailAndPassword() clears the authentication email error message on a successful sign in",
+      () async {
+        when(signInUseCase.call(invalidCredentials))
+            .thenThrow(emailAuthException);
+
+        await authNotifier.signInWithEmailAndPassword(
+            invalidEmail, invalidPassword);
```
Comment (solid-vovabeloded) [inline metrics/web/test/auth/presentation/state/auth_notifier_test.dart:317]: Would it be more pretty and readable if we'll add a trailing comma in such situations?
```suggestion
        await authNotifier.signInWithEmailAndPassword(
          invalidEmail,
          invalidPassword,
        );
```

File: metrics/web/test/auth/presentation/state/auth_notifier_test.dart [hunk 8]
```diff
@@ -235,56 +248,110 @@ void main() {
...
+        expect(authNotifier.passwordErrorMessage, isNull);
+      },
+    );
+
     test(
       ".signInWithGoogle() clears the authentication error message on a successful sign in",
-      () {
-        authNotifier.signInWithGoogle();
+      () async {
+        await authNotifier.signInWithGoogle();
```
Comment (solid-vovabeloded) [inline metrics/web/test/auth/presentation/state/auth_notifier_test.dart:347]: Should the tests of the `signInWithGoogle` method be like a previous test? I mean should we populate the `authErrorMessage` with some error and then check if a successful login clears this message?

File: metrics/web/test/auth/presentation/widgets/auth_form_test.dart [hunk 9]
```diff
@@ -53,12 +48,8 @@ void main() {
     }
 
     setUp(() {
-      authNotifier = AuthNotifier(
-        receiveAuthUpdates,
-        signInUseCase,
-        googleSignInUseCase,
-        signOutUseCase,
-      );
+      authNotifier = AuthNotifierMock();
```
Comment (solid-vovabeloded) [inline metrics/web/test/auth/presentation/widgets/auth_form_test.dart:51]: Should we add a `tearDown` to reset the auth notifier mock after each test to make sure that the tests do not influence each other? Also, if we'll do it, we'll be able to avoid creation of the separate notifier in all tests.

File: metrics/web/test/common/presentation/widgets/metrics_text_form_field_test.dart [hunk 10]
```diff
@@ -187,6 +187,22 @@ void main() {
       },
     );
 
+    testWidgets(
+      "applies the given error text as the text form field error text",
```
Comment (solid-vovabeloded) [inline metrics/web/test/common/presentation/widgets/metrics_text_form_field_test.dart:191]:
```suggestion
      "applies the given error text to the text form field error text",
```
?

File: metrics/web/test/common/presentation/widgets/metrics_text_form_field_test.dart [hunk 11]
```diff
@@ -459,6 +475,9 @@ class _MetricsTextFormFieldTestbed extends StatelessWidget {
   /// A text to apply to the text field as a label.
   final String label;
 
+  /// An error text that appears below this input field.
```
Comment (solid-vovabeloded) [inline metrics/web/test/common/presentation/widgets/metrics_text_form_field_test.dart:478]:
```suggestion
  /// An error text that appears below the [MetricsTextFormField].
```

**Review by solid-vovabeloded — CHANGES_REQUESTED** [review]
Great job, @solid-maxim & @solid-tetianamovlian! I've added a couple of suggestions - let me know what do you think. Thanks for working on those tests!

**Review by solid-vovabeloded — APPROVED** [review]
LGTM, thanks @solid-tetianamovlian & @solid-maxim!
