### PR TITLE
fix: Improve checkbox to apply the hover effect like on the designs.

### LINKED ISSUE #571: Checkbox hover behaviour
**Describe the bug**
On hover checkbox should have another background and highlight shouldn't be visible.
Current implementation:
image

Zeplin:
image

**To Reproduce**

1. Open project group modal dialog
2. Hover project list item
3. Notice that the icon is different from zeplin and the item is highlighted

**Expected behavior**
We should use the proper icon from Zeplin and item shouldn't be highlighted.

**Additional context**

### PR DESCRIPTION
**Pull request by vova-beloded**
Fixes #571 

## Checklist

- [x] Documented
- [x] Unit tested
- [x] Component tested
- [x] Driver tested

### CODE REVIEW

File: metrics/web/test/common/presentation/widgets/metrics_checkbox_test.dart [hunk 1]
```diff
@@ -77,6 +129,27 @@ void main() {
       },
     );
 
+    testWidgets(
+      "displays the animated cross fade with image for the hovered blank checkbox if the with is hovered",
```
Comment (illia-romanenko) [inline metrics/web/test/common/presentation/widgets/metrics_checkbox_test.dart:133]:
```suggestion
      "displays the animated crossfade with the image for the hovered blank checkbox if the widget is hovered",
```

File: metrics/web/test/common/presentation/widgets/metrics_checkbox_test.dart [hunk 2]
```diff
@@ -59,6 +90,27 @@ void main() {
       },
     );
 
+    testWidgets(
+      "displays the animated cross fade with image for the hovered checkbox if the widget is hovered",
```
Comment (illia-romanenko) [inline metrics/web/test/common/presentation/widgets/metrics_checkbox_test.dart:94]:
```suggestion
      "displays the animated crossfade with the image for the hovered checkbox if the widget is hovered",
```

**Review by illia-romanenko — CHANGES_REQUESTED** [review]
Looks great, thanks @vova-beloded! I've added small test description suggestions but overall looks like in the designs. Thanks for adding this one!

**Review by illia-romanenko — APPROVED** [review]
LGTM - thanks @vova-beloded !

**Comment by illia-romanenko** [comment]
@mergifyio refresh
