### PR TITLE
fix: Dashboard: Project name filter persists on navigation

### LINKED ISSUE #505: Dashboard: filter by project group name persists on navigation
**Describe the bug**
> A clear and concise description of what the bug is.

Dashboard: filter by project group name persists on the navigation Home (using project logo)
image

**To Reproduce**
> Steps to reproduce the behavior:

1. Open Dashboard
2. Filter by project name
3. Notice less projects displayed
4. Click on the app logo 
5. Notice navigation to the Home page
6. Notice project group filter input is empty
7. Notice that you still see less project as filter is still applied

**Expected behavior**
> A clear and concise description of what you expected to happen.

1. Open Dashboard
2. Filter by project name
3. Notice less projects displayed
4. Click on the app logo 
5. Notice navigation to the Home page
6. Notice project group filter input is empty
7. Notice that you still **see all of the projects**

**Additional context**
Thanks to Tetiana for spotting this issue.

### PR DESCRIPTION
**Pull request by solid-daniyilyevtyushkin**
Fixes #505 

## Checklist

- [x] Documented
- [x] Unit tested

### CODE REVIEW

File: metrics/web/lib/dashboard/presentation/pages/dashboard_page.dart [hunk 1]
```diff
@@ -31,6 +31,7 @@ class _DashboardPageState extends State<DashboardPage> {
     _projectMetricsNotifier =
         Provider.of<ProjectMetricsNotifier>(context, listen: false);
 
+    _projectMetricsNotifier.resetProjectNameFilter();
```
Comment (illia-romanenko) [inline metrics/web/lib/dashboard/presentation/pages/dashboard_page.dart:34]: I think we should just move it to the initState() as it seem to be unrelated to the subscription to the project errors.

**Review by illia-romanenko — CHANGES_REQUESTED** [review]
Thanks @solid-daniyilyevtyushkin - I've added small change request - please let me know what you think. Nice PR!

**Review by illia-romanenko — APPROVED** [review]
LGTM - thanks @solid-daniyilyevtyushkin !

**Comment by illia-romanenko** [comment]
@mergifyio refresh
