### PR TITLE
fix: Fix password visibility icon color in Light Theme

### LINKED ISSUE #615: Fix password visibility icon in the light theme
**Describe the bug**
On the login screen, password visibility icon on the light theme is white - but should be black.

**To Reproduce**
1. Open login page
2. Switch to light theme
3. Password visibility icon is white

**Expected behavior**
The password visibility icon should be black as in Zeplin

**Additional context**

### PR DESCRIPTION
**Pull request by solid-daniyilyevtyushkin**
Fixes #615 

## Checklist

- [x] Documented
- [x] Component tested

## Before
Снимок экрана 2020-09-23 в 16 41 11

## Now
Снимок экрана 2020-09-23 в 16 38 24

### CODE REVIEW

File: metrics/web/lib/common/presentation/metrics_theme/model/login_theme_data.dart [hunk 1]
```diff
@@ -9,12 +9,17 @@ class LoginThemeData {
   /// A [MetricsButtonStyle] for buttons with login options.
   final MetricsButtonStyle loginOptionButtonStyle;
 
+  /// A [Color] ot the password visibility icon color.
```
Comment (solid-vladlaba) [inline metrics/web/lib/common/presentation/metrics_theme/model/login_theme_data.dart:12]:
```suggestion
  /// A [Color] of the password visibility icon.
```

File: metrics/web/lib/common/presentation/metrics_theme/model/login_theme_data.dart [hunk 2]
```diff
@@ -9,12 +9,17 @@ class LoginThemeData {
...
+  final Color passwordVisibilityIconColor;
+
   /// Creates a new instance of the [LoginThemeData].
   ///
   /// The [loginOptionButtonStyle] defaults to an empty
   /// [MetricsButtonStyle] instance.
+  /// The [passwordVisibilityIconColor] defaults to [Colors.grey];
```
Comment (solid-vladlaba) [inline metrics/web/lib/common/presentation/metrics_theme/model/login_theme_data.dart:19]:
```suggestion
  /// If the [passwordVisibilityIconColor] is `null`, the [Colors.grey] is used.
```

File: metrics/web/test/auth/presentation/widgets/auth_form_test.dart [hunk 3]
```diff
@@ -239,6 +249,27 @@ void main() {
       },
     );
 
+    testWidgets(
+      "applies the password visibility icon color from the metrics theme",
```
Comment (solid-vladlaba) [inline metrics/web/test/auth/presentation/widgets/auth_form_test.dart:253]:
```suggestion
      "applies the color from the metrics theme to the password visibility icon",
```

File: metrics/web/test/common/presentation/metrics_theme/model/login_theme_data_test.dart [hunk 4]
```diff
@@ -14,6 +14,7 @@ void main() {
         const themeData = LoginThemeData();
 
         expect(themeData.loginOptionButtonStyle, isNotNull);
+        expect(themeData.passwordVisibilityIconColor, isNotNull);
```
Comment (solid-vladlaba) [inline metrics/web/test/common/presentation/metrics_theme/model/login_theme_data_test.dart:17]: Let's move this to the separate test and pass `null` in constructor as a value for this color.

**Review by solid-vladlaba — CHANGES_REQUESTED** [review]
Well done, @solid-daniyilyevtyushkin! I've added a couple of suggestions below - please let me know what you think! 
Also, thanks for you've noticed this issue! 👍

**Review by solid-vladlaba — APPROVED** [review]
LGTM, thanks @solid-daniyilyevtyushkin!:rocket:
