### PR TITLE
fix: Remove checkbox selection animation

### LINKED ISSUE #555: Remove checkbox selection animation
**Describe the bug**
We don't like the selection effect- (Default Material animation like InkWell) kind of glow around the box.
image

**To Reproduce**
1. Use any checkbox element
2. Notice that on selection default Splash effect applies

**Expected behavior**
No selection animation should be applied.

**Additional context**

### PR DESCRIPTION
**Pull request by solid-maxim**
Fixes #555

### CODE REVIEW

File: metrics/web/lib/project_groups/presentation/widgets/project_checkbox_list_tile.dart [hunk 1]
```diff
@@ -26,6 +26,7 @@ class ProjectCheckboxListTile extends StatelessWidget {
     return Material(
       color: Colors.transparent,
       child: InkWell(
+        highlightColor: Colors.transparent,
```
Comment (vova-beloded) [inline metrics/web/lib/project_groups/presentation/widgets/project_checkbox_list_tile.dart:29]: Maybe we can move this color to the MaterialTheme also?

**Review by vova-beloded — CHANGES_REQUESTED** [review]
Great job, @solid-maxim! I've added one suggestion here, please, let me know what do you think.

**Review by vova-beloded — APPROVED** [review]
LGTM, thanks @solid-maxim!
