### PR TITLE
fix: Remove an additional scroll stretching effect

### LINKED ISSUE #566: Remove an additional scroll stretching effect
**Describe the bug**
Default material scrolling effect applies but we don't want it to be there.
 
image

**To Reproduce**

1. Navigate to the dashboard page
2. Scroll project metrics down
3. Notice scrolling effect

**Expected behavior**
No scrolling effect should be applied across the project (for every scroll there shouldn't be any effect). Should we create some common widget for that?

**Additional context**

### PR DESCRIPTION
**Pull request by solid-dimakoniaiev**
Fixes #566

## Checklist

- [x] Documented
- [x] Unit tested

### CODE REVIEW

File: metrics/web/lib/main.dart [hunk 1]
```diff
@@ -112,3 +118,15 @@ class _MetricsAppState extends State<MetricsApp> {
     );
   }
 }
+
+/// A [ScrollBehavior] that disable the stretching effect.
+class _ScrollBehaviour extends ScrollBehavior {
```
Comment (illia-romanenko) [inline metrics/web/lib/main.dart:123]:
```suggestion
class MetricsScrollBehavior extends ScrollBehavior {
```
I think it also would be beneficial to move it to the `common/presentation/widgets` to make the `main.dart` more simple and to match Flutter's `ScrollBehavior` location (`src/widgets/scroll_configuration.dart`)

**Review by illia-romanenko — CHANGES_REQUESTED** [review]
Thanks, @solid-dimakoniaiev @solid-yuriiuvarov - looks great now!

I've added some structure suggestion - please review and let me know what you think.

The site looks more and more polished each day - thanks!

**Review by illia-romanenko — APPROVED** [review]
LGTM - thanks @solid-yuriiuvarov @solid-dimakoniaiev !

**Comment by illia-romanenko** [comment]
@mergifyio refresh
